[Fix] Bug fixes for UI
Try/OpenGothic pull request #208
Opened 2021-11-07 17:05 UTC by bwajsowicz

Description
A little patch for a couple of UI bugs I've found.

- It's no longer possible to open any menu type (MENU_MAIN, MENU_LOG etc.)
  while the game is loading or saving.
- Removed possibility to open the inventory while the dialog menu is active.

2021-11-07 18:01 UTC, Try commented
> It's no longer possible to open any menu type (MENU_MAIN, MENU_LOG etc.)

While it's inline with original, have option to pause game upfront is nice sometimes. Can you leave only a `MENU_MAIN` option?

> Removed possibility to open the inventory while the dialog menu is active.

Here a screenshoot of steam version of the game. Pretty nice feature actually)
![изображение](https://user-images.githubusercontent.com/122894/140656031-2773c75d-cde8-4968-ad7c-f617396e95d7.png)

2021-11-08 16:28 UTC, bwajsowicz commented
> While it's inline with original, have option to pause game upfront is nice sometimes. Can you leave only a MENU_MAIN option

I think it's kinda useless to have this option while the game is loading/saving. I'll stay with the legacy behaviour. Maybe let's left MENU_MAIN option only for debug build?

> Here a screenshoot of steam version of the game. Pretty nice feature actually)
That's weird - I can't do the same on the Steam version. I had to spam the backspace key while the dialog menu is opening to get the same effect as yours - can't open the inventory when dialog menu is fully active.

2021-11-08 23:49 UTC, Try commented
> Maybe let's left MENU_MAIN option only for debug build?

Yep, that's fine.

>  I had to spam the backspace/tab key while the dialog menu

Vanilla is not 100% reliable at this, but it inventory is nice to have in dialog: player can switch spells/weapons before the fight; equip/remove rings and such.

2021-11-16 22:03 UTC, Fabiosek commented
> Pretty nice feature actually)

Nope.  This causes a lot of problems. This has been fixed in the latest version of Systempack 2.0 (Union).

2021-11-17 21:39 UTC, Try commented
Hi, @Fabiosek !
It seem this inventory case is arguable. In that case can you provide some details, on what kind of problems it causes?

On my side I can say: 
1. it's nice to have an option to check(and change) equipment, before battle; 
2. and to drop the gold in the right time

2021-11-17 21:51 UTC, Fabiosek commented
> 
> 
> Hi, @Fabiosek ! It seem this inventory case is arguable. In that case can you provide some details, on what kind of problems it causes?
> 
> On my side I can say:
> 
>     1. it's nice to have an option to check(and change) equipment, before battle;
> 
>     2. and to drop the gold in the right time

2. This way you can cheat without the codes. This allows you to rob traders (check out Lord Saradoc's videos). A good game should not have such bugs. Therefore, in Union or Systempack, a lot of such stupidities from the original have been corrected (especially in Union, the newer version of systempack)

1. I don't know if you've played Gothic mods, but it's very easy to bug them that way. It is enough for you to have a dialogue that requires having a specific item. If you don't give the item back right away, you can activate dialogue this way and quickly discard the item, which will "do nothing" to the NPC. This is strong cheating. Once I described it more broadly, but I do not have this content anymore, and I do not want to repeat myself. You do as you think. But recreating Gothic 1: 1 + his mistakes is not a good idea.

2021-11-17 22:40 UTC, Try commented
> discard the item, which will "do nothing" to the NPC

Found in vanilla scripts this case: dragons do not exchange `Eye of Innos` atomically. Moving to formal code-review then.

2021-11-17 22:50 UTC, Try requested changes

2021-11-17 22:50 UTC, Try commented on game/ui/dialogmenu.cpp
> +  if(e.key==Event::K_Back) {
Inventory can be reassigned to different key

2021-11-17 22:50 UTC, Try commented on game/mainwindow.cpp
> +
should allow MENU_MAIN and F3

2022-01-29 19:16 UTC, Try commented
Discard pull request, since there is no response to requested changes.
Inventory + Dialog interaction is already covered by ffb73cad

2022-01-29 19:16 UTC, closed without merging