fix: input problem when releasing one of two mapped keys
Try/OpenGothic pull request #441
Opened 2023-04-10 17:53 UTC by PoetaKodu

## Problem

When you press a primary key action and then press the secondary one, if you then release one of the keys the action stops. Practical example:
- Press primary forward key (<kbd>W</kbd>)
- Press secondary forward key (<kbd>Up</kbd>)
- Release <kbd>W</kbd>
- **Problem:** your character stops moving forward.

## Fix

I fixed this problem by introducing tracking ([`KeyStatus`](https://github.com/Try/OpenGothic/blob/e55bb06514844881de4c239954414bf586bce01a/game/game/playercontrol.h#L78)) of both mappings: `Primary` and `Secondary`. Action is considered "on" if at least one mapped button is pressed.

2023-04-11 21:15 UTC, Try commented
Hm, looking at problem statement, I'm not sure about whole this.
* problem is not relevant to single-shoot, only for repeatable ones
* repeatable are.. movement only, right?

If problem exists exclusively for `WASD`, than redoing whole control scheme seem to be overkill to me.  We should probably look for alternatives, that are more local, preferably fully localized to PlayerControl

2023-04-11 21:20 UTC, PoetaKodu commented
We can use an approach similar to how Unreal Engine handles input. There are two types of inputs:
- Input Action - press/release events are relevant
- Input Axis - being pressed is relevant

Similar to this we can divide inputs to two groups and handle them separately. What do you think about this?

2023-04-16 12:16 UTC, PoetaKodu commented
Hi again. I finished the PR. I've implemented it in a very non-invasive way. The changes affected only the following movement input:

- fwd/bwd movement
- strafe left/right movement
- turning left/right

The way other input work was not affected.

2023-04-17 20:41 UTC, Try commented
Seems this PR can be improved and make even less invasive:
`DocumentMenu`, `InventoryMenu`, `MenuRoot` not suppose to care about mappings, only `PlayerControl::onKeyPressed/onKeyReleased` need to know about mapping.

My propose here is to keep
```
Action KeyCodec::tr(Tempest::KeyEvent& e) const;
Action KeyCodec::tr(Tempest::MouseEvent& e) const;
```
and add
```
Mapping KeyCodec::mapping(Tempest::KeyEvent& e) const;
```
and change `onKeyPressed` to take mapping  as one more argument.

2023-04-17 20:44 UTC, PoetaKodu commented
sure, I'll do it

2023-04-17 21:23 UTC, PoetaKodu commented
Done :p

2023-04-17 22:13 UTC, Try requested changes

2023-04-17 22:13 UTC, Try commented on game/game/playercontrol.cpp
> +  setAnimRotate(pl, rot, ani==Npc::Anim::Idle ? rotation : 0, movement.turnRight.any(), dt);
Naming `turnRight` is somewhat confusing, makes reader thing, that there is `turnLeft` somewhere. Maybe simply `turn`?

2023-04-17 22:13 UTC, Try commented on game/game/playercontrol.h
> +        std::array<bool, 2> main;
Should it be `NumAxes`, instead of 2? Or maybe something like `KeyCodec::NumMappings`?

2023-04-17 22:13 UTC, Try commented on game/game/playercontrol.h
> +        auto modifier() const -> float {
code: `auto modifier()`
comment: `current axis value`

Maybe `auto value() const` is a better name? Also no need to do so many comment and empty lines - code is quite readable as-is

2023-04-17 22:31 UTC, PoetaKodu commented
I've applied the requested changes. The only thing I did different is with `turn` and other names. By changing `turnRight` to `turn` I'd have to also change `strafeRight` to `strafe` which would be misleading.

2023-04-18 19:41 UTC, merged

2023-04-18 19:42 UTC, Try commented
I've made a few more code-style changed, and merged. Thanks!