Add `goto vob` and `goto camera` marvin commands
Try/OpenGothic pull request #634
Opened 2024-05-24 13:47 UTC by thokkat

`goto vob` teleports the player to a vob that matches the given name.  A index number can be added to teleport to the n_th vob in case there exist multiple, often the case for items. Only npcs and items are tested for now but in vanilla it works for all kind of vobs.

`goto camera` teleports the player to the camera position. I found this came in handy when I wanted to observe a npc without percs being triggered but then move quickly to the scene to look what would happen.

2024-05-24 14:24 UTC, Try approved these changes

2024-05-24 14:34 UTC, thokkat commented
> will merge after finishing my work with sky
Sure no hurry. Just some pr/issue spam incoming from my side. Want to wrap up stuff lying around :)

2024-05-26 17:59 UTC, Try requested changes

2024-05-26 17:59 UTC, Try commented on game/world/worldobjects.cpp
> +  if(n==0)
Normally in C++ indexing is normally zero-based. 
I'm suggesting to have this function as zero-based, and in that case `-1` passed from caller will be casted to `UINT_MAX` and result into null result.

2024-05-26 17:59 UTC, Try commented on game/world/world.h
> +    Item*                findItemByInstance(size_t instance, uint32_t n = 1);
In project indices are nominated in `size_t`, not uint

2024-05-26 21:10 UTC, merged

2024-05-26 21:10 UTC, Try commented
Merged, thanks!